apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gpsd-vfy-engine
  labels:
    app: {{ .Release.Name }}-gpsd-vfy-engine
spec:
  ports:
    {{- range .Values.service }}
    - name: {{ .name | default "http" }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}-gpsd-vfy-engine
  {{- with .Values.service | first }}
  type: {{ .type | default "ClusterIP" }}
  {{- end }}